# coding: utf-8

"""
    IMDb-API

    The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>  # noqa: E501

    OpenAPI spec version: 1.5
    Contact: support@imdb-api.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SimilarShort(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'title': 'str',
        'full_title': 'str',
        'year': 'str',
        'image': 'str',
        'plot': 'str',
        'directors': 'str',
        'stars': 'str',
        'genres': 'str',
        'im_db_rating': 'str'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'full_title': 'fullTitle',
        'year': 'year',
        'image': 'image',
        'plot': 'plot',
        'directors': 'directors',
        'stars': 'stars',
        'genres': 'genres',
        'im_db_rating': 'imDbRating'
    }

    def __init__(self, id=None, title=None, full_title=None, year=None, image=None, plot=None, directors=None, stars=None, genres=None, im_db_rating=None):  # noqa: E501
        """SimilarShort - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._title = None
        self._full_title = None
        self._year = None
        self._image = None
        self._plot = None
        self._directors = None
        self._stars = None
        self._genres = None
        self._im_db_rating = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if title is not None:
            self.title = title
        if full_title is not None:
            self.full_title = full_title
        if year is not None:
            self.year = year
        if image is not None:
            self.image = image
        if plot is not None:
            self.plot = plot
        if directors is not None:
            self.directors = directors
        if stars is not None:
            self.stars = stars
        if genres is not None:
            self.genres = genres
        if im_db_rating is not None:
            self.im_db_rating = im_db_rating

    @property
    def id(self):
        """Gets the id of this SimilarShort.  # noqa: E501


        :return: The id of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this SimilarShort.


        :param id: The id of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def title(self):
        """Gets the title of this SimilarShort.  # noqa: E501


        :return: The title of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this SimilarShort.


        :param title: The title of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def full_title(self):
        """Gets the full_title of this SimilarShort.  # noqa: E501


        :return: The full_title of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._full_title

    @full_title.setter
    def full_title(self, full_title):
        """Sets the full_title of this SimilarShort.


        :param full_title: The full_title of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._full_title = full_title

    @property
    def year(self):
        """Gets the year of this SimilarShort.  # noqa: E501


        :return: The year of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._year

    @year.setter
    def year(self, year):
        """Sets the year of this SimilarShort.


        :param year: The year of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._year = year

    @property
    def image(self):
        """Gets the image of this SimilarShort.  # noqa: E501


        :return: The image of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this SimilarShort.


        :param image: The image of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._image = image

    @property
    def plot(self):
        """Gets the plot of this SimilarShort.  # noqa: E501


        :return: The plot of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._plot

    @plot.setter
    def plot(self, plot):
        """Sets the plot of this SimilarShort.


        :param plot: The plot of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._plot = plot

    @property
    def directors(self):
        """Gets the directors of this SimilarShort.  # noqa: E501


        :return: The directors of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._directors

    @directors.setter
    def directors(self, directors):
        """Sets the directors of this SimilarShort.


        :param directors: The directors of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._directors = directors

    @property
    def stars(self):
        """Gets the stars of this SimilarShort.  # noqa: E501


        :return: The stars of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._stars

    @stars.setter
    def stars(self, stars):
        """Sets the stars of this SimilarShort.


        :param stars: The stars of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._stars = stars

    @property
    def genres(self):
        """Gets the genres of this SimilarShort.  # noqa: E501


        :return: The genres of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._genres

    @genres.setter
    def genres(self, genres):
        """Sets the genres of this SimilarShort.


        :param genres: The genres of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._genres = genres

    @property
    def im_db_rating(self):
        """Gets the im_db_rating of this SimilarShort.  # noqa: E501


        :return: The im_db_rating of this SimilarShort.  # noqa: E501
        :rtype: str
        """
        return self._im_db_rating

    @im_db_rating.setter
    def im_db_rating(self, im_db_rating):
        """Sets the im_db_rating of this SimilarShort.


        :param im_db_rating: The im_db_rating of this SimilarShort.  # noqa: E501
        :type: str
        """

        self._im_db_rating = im_db_rating

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SimilarShort, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SimilarShort):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
